# ─────────────────────────────
# Portfolio di Mattia Russo
# Tema: Minimal
# ─────────────────────────────

title: Mattia Russo
logo: /assets/img/Foto.png
description: My portfolio of projects from the MSc in Data Science at the University of Essex
theme: jekyll-theme-minimal
show_downloads: false
lang: en

# ─────────────────────────────
# CSS personalizzato
# ─────────────────────────────

custom_css: /assets/css/style.css

# ─────────────────────────────
# Plugins (se vuoi usare feed, SEO ecc.)
# ─────────────────────────────

plugins:
  - jekyll-feed

# ─────────────────────────────
# URL / baseurl (per GitHub Pages)
# ─────────────────────────────

url: "https://matt9891-stack.github.io"  # Sostituisci con il tuo username
baseurl: "/portfolio"                    # Sostituisci con il nome della repo

# ─────────────────────────────
# Include files particolari (opzionale)
# ─────────────────────────────

include:
  - assets/css/style.css
